server:
  port: 9090
spring:
  application:
    name: SpringTest
  config:
    activate:
      on-profile: default
  dataresource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mysql?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 0722
  jpa:
      open-in-view: true
      hibernate:
        ddl-auto: create
        naming:
          physical-strategy:
            org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardlmpl
          use-new-id-generator-mapping: false
        show-sql: true
        properties:
          hibernate:
            format_sql: true
            dialect: org.hibernate.dialect.MySQL8lnnoDBDialect
logging:
  level:
    org.hibernate.SQL: debug
